__title__ = 'mindsdb_forecast_visualizer'
__package_name__ = 'mindsdb_forecast_visualizer'
__version__ = '0.2.3'
__description__ = "Companion package to visualizer forecasts made with MindsDB predictors."
__email__ = "community@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb_forecast_visualizer'
__pypi__ = 'https://pypi.org/project/mindsdb_forecast_visualizer'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2021- mindsdb'
